help: ## Mostrar ayuda
	    @sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)

build: ##construir carpeta dist
	hugo -D > /dev/null 2>&1

.PHONY: clean
clean: ##limpiar carpeta dist
	rm -rf ./dist/ /dev/null 2>&1

post: ##crear arcchivo con titulo
	hugo new posts/$(POST_NAME).md 
	echo '--- \ntitle: "$(POST_TITLE)"\ndate: 2022-01-20T08:47:25+01:00 \ndraft: false\n---' > ./content/posts/$(POST_NAME).md
