name: module3_task1
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5,17 * * *'
  workflow_call:

jobs:
  yamllint:
    name: 'module3_task1'
    runs-on: ubuntu-18.04
    steps:
      - uses: ./.github/actions/my-action
      - name: 'Check out repository code'
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - name: 'moviendonos a module3_task1'
        working-directory: ./module3_task1
        run: sh ./setup.sh
      - name: 'moviendonos a module3_task1'
        working-directory: ./module3_task1
        run: make lint
      - name: 'moviendonos a module3_task1'
        working-directory: ./module3_task1
        run: make build
      - name: 'moviendonos a module3_task1'
        working-directory: ./module3_task1
        run: make unit-tests
      - name: 'moviendonos a module3_task1'
        working-directory: ./module3_task1
        run: make validate
      - name: 'moviendonos a module3_task1'
        working-directory: ./module3_task1
        run: make integration-tests
      
