name: module3_task2
on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: danieltendero/validation/.github/workflows/module3_task1.yml@main
    with:
      username: danieltendero
    secrets:
      token: ${{ secrets.TOKEN }}
