

name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - run: pwd
      - run: ls -la /home/runner/work/validation
      - run: ls -la
      - run: ls -la /home/runner/work
      - run: ls -la /home/runner
      - run: ls -la /home
