name: module3_task2
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5,17 * * *'
  pull_request:
    branches:
      - main

jobs:
   call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
